source :rubygems

#Classy web-development dressed in a DSL (official / canonical repo) http://www.sinatrarb.com/
gem 'sinatra'
#A service manager that helps start and stop services, for example, when testing the interaction between processes in an automated integration test http://github.com/leadtune/service_ma…
gem 'service_manager'
#Databases on Rails. Build a persistent domain model by mapping database tables to Ruby classes. Strong conventions for associations, validations, aggregations, migrations, and testing come baked-in.
gem 'activerecord'
#This module allows Ruby programs to interface with the SQLite3 database engine (http://www.sqlite.org). You must have the SQLite engine installed in order to build this module. Note that this module is only compatible with SQLite 3.6.16 or newer.
gem 'sqlite3'

group :development do
	gem 'rspec'
	gem 'cucumber'
	gem 'capybara'
	gem 'launchy'
	gem 'database_cleaner'
end