# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 504fd6402e091eacb54d3fa4c486f305769b10dc62966c08466cc793828fb65023fedf066bf0a9eda51b97c9f170df93e76f1b0fce4d708bd163827e24043fd9

test:
  secret_key_base: 05556d00c51181e7db6c9c3612f349e6896f395b0091ad51d84f9c29345cd79afdb5762628096a837e6f2431f24cfdba474b4d976671d4f402e417bb12a98096

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
