# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f3851f209ebf4a1a8ec1be646dffc8684c8e7b8e69ccd37aa9139c5a1bb0d2194fafbfea5661246605d9134418906e91abc3e15e027b3b93dd2813d6fd9f75e

test:
  secret_key_base: cbee68cea911a1957cb958630139176c74e62d67797827450ccc9de9d8edcd6883ad1b9c0f25804e1a1f0f71f7d9dfa9ce65654d2b606d80ff34f0338b61a44a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
