source 'https://rubygems.org'

#Classy web-development dressed in a DSL (official / canonical repo) http://www.sinatrarb.com/
gem 'sinatra'
#JSON implementation for Ruby http://flori.github.com/json
gem 'json'

group :test do
	gem 'cucumber'
	gem 'rspec'
	#gem 'rack-test' #not use it anymore because we are not use to talk with to web server
	gem 'httparty'
	gem 'childprocess'
end